<h1> Respostas para Dados - Q1 - Notebook </h1>

Olá leitor, este notebook tem como objetivo apresentar a solução da Q1 da cadeira de dados.

Então vamos lá!

Primeiro decidi separar a questão em tópicos para mais fácil compreensão deste material. Caso queira ver a questão completa, acessar o README.md desse diretório

<h2> Parte 1 - Importando bibliotecas </h2>

Primeiro vamos importar as bibliotecas utilizadas neste projeto:

In [97]:
#Importando bibliotecas
import pandas as pd
import requests
import pickle
import sys
from datetime import datetime, timedelta

<h2> Parte 2 - Obtenha </h2>

Obtenha (1 pt todos):

- a lista de estações automáticas.
- uma série de 14 dias contendo todas as variáveis da uma estação qualquer.

<br> Resposta </br>

Para obter essas duas repostas basta usar request, seguindo a [documentação da API](https://portal.inmet.gov.br/manual/manual-de-uso-da-api-esta%C3%A7%C3%B5es).

Primeira coisa que faremos são algumas funções para nos auxiliarem na montagem dessas requisições. Vamos lá.

In [141]:
#Função 1
def datas_requisicao(delta=14):
    '''
    Função para aquisição e tratamento de datas.

    Input: Inteiro(delta) representando o intervalo de dias para requisição. 
           Delta Default de 14 dias, como pedido na requisição do programa. 

    Output: Data de hoje e Data passada (-14 dias)
    
    OBSERVAÇÃO: foi visto que chegando a dias mais atuais as estação nao subiram seus dados climaticos. 
    Então se você observar, decidi não usar essa função na url_requisições(), ao invés coloquei as datas manualmente. 
    Porém a função funciona normalmente, basta descomentar 
    a 4° linha da função url_requisição 
    '''
    
    data_hoje = datetime.today()
    delta_entre_datas = delta
    data_passado = data_hoje - timedelta(days=delta_entre_datas)

    data_hoje_requisicao = data_hoje.strftime('%Y-%m-%d')
    data_passada_requisicao = data_passado.strftime('%Y-%m-%d')
  
    return data_passada_requisicao, data_hoje_requisicao

#Função 2
def url_requisicoes(tipo_estacao='T', codigo_estacao='A247'):
    '''
    Função para a 'fabricação' da requisição da API do INMET. 
    Ver documentação em: https://portal.inmet.gov.br/manual/manual-de-uso-da-api-esta%C3%A7%C3%B5es

    Input: Tipo da estação T ou M para primeira requisição. 
           Codigo da estacao para segunda requisição

    Output: Duas URL montadas para a requisição via API
    
    LER OBSERVAÇÃO da primeira função

    '''
    print (datas_requisicao()[0])
    print (datas_requisicao()[1])
    url_estacoes = f'https://apitempo.inmet.gov.br/estacoes/{tipo_estacao}'
    #LEIA A OBSERVAÇÃO DA PRIMIRA FUNÇÃO
    #url_estacoes_dadosdiarios = f'https://apitempo.inmet.gov.br/estacao/diaria/{datas_requisisao()[0]}/{datas_requisisao()[1]}/{codigo_estacao}'  
    data1 = "2019-07-01"
    data2 = "2019-07-14"
    url_estacoes_dadosdiarios = f'https://apitempo.inmet.gov.br/estacao/diaria/{data1}/{data2}/{codigo_estacao}'
    print (url_estacoes_dadosdiarios)
    return url_estacoes, url_estacoes_dadosdiarios

#Função 3

def requisicao_lista_estacao():
    """
    Função para requisição de lista das estações, gerando arquivo ListaEstacoes.json na pasta resposta_json
    """
    try:
        lista_estacoes = requests.get(url_requisicoes()[0])
        lista_estacoes_json = lista_estacoes.json()
        lista_estacoes.raise_for_status()
        with open('json/ListaEstacoes.json', 'wb') as dj:
            pickle.dump(lista_estacoes_json, dj)
        print("Requisição Lista de estações finalizado com Sucesso!")

    # Tratamento de erros
    except requests.exceptions.HTTPError as errh:
        print("Http Error:", errh)
    except requests.exceptions.ConnectionError as errc:
        print("Error Connecting:", errc)
    except requests.exceptions.Timeout as errt:
        print("Timeout Error:", errt)
    except requests.exceptions.RequestException as err:
        print("OOps: Something Else", err)
        
#Função 4
def requisicao_serie_dias():
    """
    Função para requisição de serie de dias, gerando arquivo SerieDias.json na pasta resposta_json
    """
    try:
        serie_dias = requests.get(url_requisicoes()[1])
        serie_dias_json = serie_dias.json()
        serie_dias.raise_for_status()
        with open('json/SerieDias.json', 'wb') as dj:
            pickle.dump(serie_dias_json, dj)
        print("Requisicção serie dias finalizado com Sucesso!")

    # Tratamento de erros
    except requests.exceptions.HTTPError as errh:
        print("Http Error:", errh)
    except requests.exceptions.ConnectionError as errc:
        print("Error Connecting:", errc)
    except requests.exceptions.Timeout as errt:
        print("Timeout Error:", errt)
    except requests.exceptions.RequestException as err:
        print("OOps: Something Else", err)  
        
#Função 5
def carregamento1_listaestacoes():
    '''
    Função para o carramento do arquivo json na main.
    Não é necessária esta função, porém ela se faz util caso o usuário queira visualizar o Json

    Output: variavel com dados .json gravados.
    '''

    try:
        with open('json/ListaEstacoes.json', 'rb') as fp:
            listas_estacoes = pickle.load(fp)
            return listas_estacoes
    except FileNotFoundError:
        print('Está faltando o arquivo ListaEstacoes.json')
        sys.exit(-1)

#Função 6
def carregamento2_serie_dias():
    '''
    Função para o carramento do arquivo .json na main.
    Não é necessária esta função, porém ela se faz util caso o usuário queira visualizar o Json

    Output: variavel com dados .json gravados.
    '''

    try:
        with open('json/SerieDias.json', 'rb') as fp:
            serie_dias = pickle.load(fp)
            return serie_dias
    except FileNotFoundError:
        print('Está faltando o arquivo SerieDias.json')
        sys.exit(-1)

<h3> Resposta Parte 2 </h3>

In [142]:
requisicao_lista_estacao()
requisicao_serie_dias()

2021-09-22
2021-10-06
https://apitempo.inmet.gov.br/estacao/diaria/2019-07-01/2019-07-14/A247
Requisição Lista de estações finalizado com Sucesso!
2021-09-22
2021-10-06
https://apitempo.inmet.gov.br/estacao/diaria/2019-07-01/2019-07-14/A247
Requisicção serie dias finalizado com Sucesso!

<h2> Parte 3 - Consolide </h2>

Consolide (1 pt todos):

- a lista das estações automáticas em um dataframe.
- a série de 14 dias de dados em um dataframe.

In [143]:
listas_estacoes_json = carregamento1_listaestacoes()
serie_dias_json = carregamento2_serie_dias()

In [144]:
listas_estacoes_df = pd.DataFrame.from_dict(
    listas_estacoes_json, orient='columns')

serie_dias_df = pd.DataFrame.from_dict(
    serie_dias_json, orient='columns')

In [145]:
listas_estacoes_df

,CD_OSCAR,DC_NOME,FL_CAPITAL,DT_FIM_OPERACAO,CD_SITUACAO,TP_ESTACAO,VL_LATITUDE,CD_WSI,CD_DISTRITO,VL_ALTITUDE,SG_ESTADO,SG_ENTIDADE,CD_ESTACAO,VL_LONGITUDE,DT_INICIO_OPERACAO
0,0-2000-0-86765,ABROLHOS,N,None,Pane,Automatica,-17.96305555,0-76-0-2906907000000408,04,20.93,BA,INMET,A422,-38.70333333,2008-07-20T21:00:00.000-03:00
1,0-2000-0-81755,ACARAU,N,None,Pane,Automatica,-3.1211111,0-76-0-2300200000000446,03,67.15,CE,INMET,A360,-40.08722221,2009-04-21T21:00:00.000-03:00
2,0-2000-0-86827,AFONSO CLAUDIO,None,None,Pane,Automatica,-20.10416666,0-76-0-3200102000000478,06,507.48,ES,INMET,A657,-41.10694444,2011-09-23T21:00:00.000-03:00
3,0-2000-0-86686,AGUA BOA,N,None,Pane,Automatica,-14.01638888,0-76-0-5100201000000157,09,440,MT,INMET,A908,-52.21166666,2006-12-15T21:00:00.000-03:00
4,0-2000-0-86812,AGUA CLARA,N,None,Operante,Automatica,-20.44444444,0-76-0-5000203000000463,07,323.63,MS,INMET,A756,-52.87583332,2010-08-13T21:00:00.000-03:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,0-2000-0-86697,VITORIA DA CONQUISTA,N,None,Pane,Automatica,-14.88638888,0-76-0-2933307000000204,04,879.38,BA,INMET,A414,-40.80138888,2007-05-31T21:00:00.000-03:00
601,0-2000-0-86815,VOTUPORANGA,N,None,Operante,Automatica,-20.40333333,0-76-0-3557105000000154,07,510.37,SP,INMET,A729,-49.96611111,2006-12-03T21:00:00.000-03:00
602,0-2000-0-86940,XANXERE,N,None,Operante,Automatica,-26.938666,0-76-0-4219507000000318,08,878.74,SC,INMET,A858,-52.39809,2008-03-14T21:00:00.000-03:00
603,0-2000-0-81896,XINGUARA,N,None,Operante,Automatica,-7.110518,0-76-0-1508407000000527,02,245,PA,INMET,A247,-49.926072,2016-09-10T21:00:00.000-03:00
604,0-2000-0-81747,ZE DOCA,N,None,Operante,Automatica,-3.26916666,0-76-0-2114007000000596,02,45.5,MA,INMET,A255,-45.65111111,2019-09-17T21:00:00.000-03:00

In [146]:
serie_dias_df

,UMID_MED,DT_MEDICAO,DC_NOME,UMID_MIN,TEMP_MED,CHUVA,VL_LATITUDE,TEMP_MIN,TEMP_MAX,UF,VEL_VENTO_MED,CD_ESTACAO,VL_LONGITUDE
0,67.5,2019-07-01,XINGUARA,40,25.8,0,-7.110518,18.4,34,PA,None,A247,-49.926072
1,66.5,2019-07-02,XINGUARA,36,26.1,0,-7.110518,18.2,34.7,PA,None,A247,-49.926072
2,67.4,2019-07-03,XINGUARA,42,26.3,0,-7.110518,19.9,34,PA,None,A247,-49.926072
3,71.6,2019-07-04,XINGUARA,43,26.3,0,-7.110518,20,34.7,PA,None,A247,-49.926072
4,72.3,2019-07-05,XINGUARA,44,26.8,0,-7.110518,20.6,34.7,PA,None,A247,-49.926072
5,74,2019-07-06,XINGUARA,47,26.9,0,-7.110518,21.3,34.4,PA,None,A247,-49.926072
6,70.1,2019-07-07,XINGUARA,42,26.7,0,-7.110518,23,32.9,PA,None,A247,-49.926072
7,77.5,2019-07-08,XINGUARA,56,25.5,1,-7.110518,22.1,31,PA,None,A247,-49.926072
8,79,2019-07-09,XINGUARA,52,25,20.4,-7.110518,21.7,30.5,PA,None,A247,-49.926072
9,72,2019-07-10,XINGUARA,43,25.3,0,-7.110518,19.6,32.6,PA,None,A247,-49.926072
10,71.9,2019-07-11,XINGUARA,45,25.1,0,-7.110518,18.3,33.3,PA,None,A247,-49.926072
11,71.2,2019-07-12,XINGUARA,43,26,0,-7.110518,19,33.4,PA,None,A247,-49.926072
12,72,2019-07-13,XINGUARA,45,25.7,0,-7.110518,19.2,33.3,PA,None,A247,-49.926072
13,68.8,2019-07-14,XINGUARA,38,26,0,-7.110518,19.6,34.1,PA,None,A247,-49.926072

<h3> Resposta parte 3 </h3

In [1]:
listas_estacoes_df.head()

NameError: name 'listas_estacoes_df' is not defined